// Code generated by github.com/swaggest/json-cli v1.8.3, DO NOT EDIT.

// Package transaction contains JSON mapping structures.
package transaction

import (
	"time"

	"github.com/nhatthm/moneyloverapi/pkg/category"
	"github.com/nhatthm/moneyloverapi/pkg/user"
	"github.com/nhatthm/moneyloverapi/pkg/wallet"
)

// Transaction structure is generated from "#/components/schemas/Transaction".
type Transaction struct {
	ID         string            `json:"_id"`              // Required.
	Note       string            `json:"note"`             // Required.
	Account    wallet.Wallet     `json:"account"`          // Required.
	Category   category.Category `json:"category"`         // Required.
	Amount     float64           `json:"amount,omitempty"` // Format: double.
	LastEditBy user.User         `json:"lastEditBy,omitempty"`
	Longitude  float64           `json:"longitude,omitempty"` // Format: float.
	Latitude   float64           `json:"latitude,omitempty"`  // Format: float.
	Address    string            `json:"address,omitempty"`
	// Format: date-time.
	// Required.
	DisplayDate   time.Time `json:"displayDate"`
	Remind        int64     `json:"remind,omitempty"`
	ExcludeReport bool      `json:"exclude_report,omitempty"`
	// Format: date-time.
	// Required.
	CreatedAt time.Time `json:"createdAt"`
}
