// Code generated by github.com/swaggest/json-cli v1.8.3, DO NOT EDIT.

// Package wallet contains JSON mapping structures.
package wallet

import (
	"github.com/nhatthm/moneyloverapi/pkg/user"
)

// Wallet structure is generated from "#/components/schemas/Wallet".
type Wallet struct {
	ID                      string      `json:"_id"`  // Required.
	Name                    string      `json:"name"` // Required.
	CurrencyID              int64       `json:"currency_id,omitempty"`
	Owner                   string      `json:"owner,omitempty"`
	SortIndex               int64       `json:"sortIndex,omitempty"`
	TransactionNotification bool        `json:"transaction_notification,omitempty"`
	Archived                bool        `json:"archived,omitempty"`
	AccountType             int64       `json:"account_type,omitempty"`
	ExcludeTotal            bool        `json:"exclude_total,omitempty"`
	Icon                    string      `json:"icon,omitempty"`
	IsDelete                bool        `json:"isDelete,omitempty"`
	ListUser                []user.User `json:"listUser,omitempty"`
}
