// Code generated by github.com/swaggest/json-cli v1.8.3, DO NOT EDIT.

// Package wallet contains JSON mapping structures.
package wallet

// WalletAll is a special wallet, indicates all wallets.
var WalletAll = Wallet{ID: "all"}
