// Code generated by github.com/swaggest/swac v0.1.19, DO NOT EDIT.

package api

import (
	"time"

	"github.com/nhatthm/moneyloverapi/internal/types"
	"github.com/nhatthm/moneyloverapi/pkg/category"
	"github.com/nhatthm/moneyloverapi/pkg/transaction"
)

// LoginResponse structure is generated from "#/components/schemas/LoginResponse".
type LoginResponse struct {
	Error  int64             `json:"error,omitempty"`
	Msg    string            `json:"msg,omitempty"`
	Action string            `json:"action,omitempty"`
	Data   LoginResponseData `json:"data"` // Required.
}

// LoginResponseData structure is generated from "#/components/schemas/LoginResponse->data".
type LoginResponseData struct {
	Status       bool   `json:"status,omitempty"`
	RequestToken string `json:"request_token,omitempty"`
	// Format: uri.
	// Required.
	LoginURL string `json:"login_url"`
}

// TokenRequest structure is generated from "#/components/schemas/TokenRequest".
type TokenRequest struct {
	ClientInfo bool `json:"client_info,omitempty"`
	// Format: email.
	// Required.
	Email string `json:"email"`
	// Format: password.
	// Required.
	Password string `json:"password"`
}

// TokenResponse structure is generated from "#/components/schemas/TokenResponse".
type TokenResponse struct {
	Status bool `json:"status,omitempty"`
	// Format: byte.
	// Required.
	AccessToken string           `json:"access_token"`
	Expire      types.UnixString `json:"expire"` // Required.
	// Format: byte.
	// Required.
	RefreshToken string                   `json:"refresh_token"`
	ClientInfo   *TokenResponseClientInfo `json:"client_info,omitempty"`
}

// TokenResponseClientInfo structure is generated from "#/components/schemas/TokenResponse->client_info".
type TokenResponseClientInfo struct {
	Name     string `json:"name,omitempty"`
	Internal bool   `json:"internal,omitempty"`
}

// ListCategoryResponse structure is generated from "#/components/schemas/ListCategoryResponse".
type ListCategoryResponse struct {
	Error  int64                   `json:"error,omitempty"`
	Msg    string                  `json:"msg,omitempty"`
	Action string                  `json:"action,omitempty"`
	Data   []category.FlatCategory `json:"data"` // Required.
}

// ListTransactionRequest structure is generated from "#/components/schemas/ListTransactionRequest".
type ListTransactionRequest struct {
	WalletID string `json:"walletId"` // Required.
	// Format: date-time.
	// Required.
	StartDate time.Time `json:"startDate"`
	// Format: date-time.
	// Required.
	EndDate time.Time `json:"endDate"`
}

// ListTransactionResponse structure is generated from "#/components/schemas/ListTransactionResponse".
type ListTransactionResponse struct {
	Error  int64                       `json:"error,omitempty"`
	Msg    string                      `json:"msg,omitempty"`
	Action string                      `json:"action,omitempty"`
	Data   ListTransactionResponseData `json:"data"` // Required.
}

// ListTransactionResponseData structure is generated from "#/components/schemas/ListTransactionResponse->data".
type ListTransactionResponseData struct {
	Daterange    *ListTransactionResponseDataDaterange `json:"daterange,omitempty"`
	Transactions []transaction.Transaction             `json:"transactions"` // Required.
}

// ListTransactionResponseDataDaterange structure is generated from "#/components/schemas/ListTransactionResponse->data->daterange".
type ListTransactionResponseDataDaterange struct {
	StartDate string `json:"startDate,omitempty"` // Format: date.
	EndDate   string `json:"endDate,omitempty"`   // Format: date.
}
