// Code generated by github.com/swaggest/json-cli v1.8.3, DO NOT EDIT.

// Package user contains JSON mapping structures.
package user

// User structure is generated from "#/components/schemas/User".
type User struct {
	ID string `json:"_id"` // Required.
	// Format: email.
	// Required.
	Email string `json:"email"`
}
